% Generate error reports for all components

clearvars
close all
clc
ObjectFactory.delete_serialized_objects

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(genpath(fullfile(root,'src')))

%% Flow predictors

fprintf('Generating report for SimulationFlowPredictor :::::::::::::::\n');
SimulationFlowPredictor.run_and_report_error( struct( ...
    'ppt_file'         , 'flow_predictor_simulation' , ...
    'xls_file'         , 'flow_predictor_simulation' , ...
    'config'           , '210E' , ...
    'output_dt'        , 300 , ...
    'end_time'         , 86400 , ...
    'update_dt'        , 900 , ...
    'horizon'          , 3600 ) );

fprintf('Generating report for ZOHFlowPredictor ::::::::::::::::::::::\n');
ZOHFlowPredictor.run_and_report_error( struct( ...
    'ppt_file'         , 'flow_predictor_zoh' , ...
    'xls_file'         , 'flow_predictor_zoh' , ...
    'config'           , '210E' , ...
    'output_dt'        , 300 , ...
    'end_time'         , 86400 , ...
    'update_dt'        , 900 , ...
    'horizon'          , 3600 ) );

fprintf('Generating report for HistoricalFlowPredictor :::::::::::::::\n');
HistoricalFlowPredictor.run_and_report_error( struct( ...
    'ppt_file'         , 'flow_predictor_historical' , ...
    'xls_file'         , 'flow_predictor_historical' , ...
    'config'           , '210E' , ...
    'output_dt'        , 300 , ...
    'end_time'          , 86400 , ...
    'update_dt'        , 900 , ...
    'horizon'          , 3600 ) );
    
fprintf('Generating report for ScaledHistoricalFlowPredictor :::::::::\n');
ScaledHistoricalFlowPredictor.run_and_report_error( struct( ...
    'ppt_file'         , 'flow_predictor_scaled_historical' , ...
    'xls_file'         , 'flow_predictor_scaled_historical' , ...
    'config'           , '210E' , ...
    'output_dt'        , 300 , ...
    'end_time'         , 86400 , ...
    'update_dt'        , 900 , ...
    'horizon'          , 3600 ) );

day=735915;
num_of_pred_Horizon=2;
fprintf('Generating report for ArmaxFlowPredictor ::::::::::::::::::::\n');
RecursiveArmaxFlowPredictor.run_and_report_error( struct( ...
    'ppt_file'         , strcat('flow_predictor_armax_', num2str(day),'_',num2str(num_of_pred_Horizon)) , ...
    'xls_file'         , strcat('flow_predictor_armax_', num2str(day),'_',num2str(num_of_pred_Horizon)) , ...
    'config'           , '210E' , ...
    'output_dt'        , 300 , ...
    'end_time'         , 86400 , ...
    'update_dt'        , 900 , ...
    'horizon'          , 3600 ,...
    'day'              , day ,...
    'num_of_pred_Horizon', num_of_pred_Horizon));

%% Demand predictors

fprintf('Generating report for Simulation DemandPredictor ::::::::::::\n');
DemandPredictor.run_and_report_error( struct( ...
    'ppt_file'           , 'demand_predictor_simulation' , ...
    'xls_file'           , 'demand_predictor_simulation' , ...
    'flow_predictor_type', 'simulation' , ...
    'config'             , '210E' , ...
    'output_dt'          , 300 , ...
    'end_time'           , 86400 , ...
    'update_dt'          , 900 , ...
    'horizon'            , 3600 ) );

fprintf('Generating report for ZOH DemandPredictor :::::::::::::::::::\n');
DemandPredictor.run_and_report_error( struct( ...
    'ppt_file'           , 'demand_predictor_historical' , ...
    'xls_file'           , 'demand_predictor_historical' , ...
    'flow_predictor_type', 'historical' , ...
    'config'             , '210E' , ...
    'output_dt'          , 300 , ...
    'end_time'           , 86400 , ...
    'update_dt'          , 900 , ...
    'horizon'            , 3600 ) );

fprintf('Generating report for ScaledHistorical DemandPredictor ::::::\n');
DemandPredictor.run_and_report_error( struct( ...
    'ppt_file'           , 'demand_predictor_armax' , ...
    'xls_file'           , 'demand_predictor_armax' , ...
    'flow_predictor_type', 'recursiveARMAX' , ...
    'config'             , '210E' , ...
    'output_dt'          , 300 , ...
    'end_time'           , 86400 , ...
    'update_dt'          , 900 , ...
    'horizon'            , 3600 ) );

%% Split ratio predictors

fprintf('Generating report for Simulation SplitPredictor ::::::::::::::\n');
SplitPredictor.run_and_report_error( struct( ...
    'ppt_file'           , 'splits_predictor_simulation' , ...
    'xls_file'           , 'splits_predictor_simulation' , ...
    'flow_predictor_type', 'simulation' , ...
    'config'             , '210E' , ...
    'output_dt'          , 300 , ...
    'end_time'           , 86400 , ...
    'update_dt'          , 900 , ...
    'horizon'            , 3600 ) );

fprintf('Generating report for ZOH SplitPredictor ::::::::::::::::::::\n');
SplitPredictor.run_and_report_error( struct( ...
    'ppt_file'           , 'splits_predictor_zoh' , ...
    'xls_file'           , 'splits_predictor_zoh' , ...
    'flow_predictor_type', 'zoh' , ...
    'config'             , '210E' , ...
    'output_dt'          , 300 , ...
    'end_time'           , 86400 , ...
    'update_dt'          , 900 , ...
    'horizon'            , 3600 ) );

fprintf('Generating report for Historical SplitPredictor :::::::::::::\n');
SplitPredictor.run_and_report_error( struct( ...
    'ppt_file'           , 'splits_predictor_historical' , ...
    'xls_file'           , 'splits_predictor_historical' , ...
    'flow_predictor_type', 'historical' , ...
    'config'             , '210E' , ...
    'output_dt'          , 300 , ...
    'end_time'           , 86400 , ...
    'update_dt'          , 900 , ...
    'horizon'            , 3600 ) );

fprintf('Generating report for Scaled Historical SplitPredictor ::::::\n');
SplitPredictor.run_and_report_error( struct( ...
    'ppt_file'           , 'splits_predictor_scaled_historical' , ...
    'xls_file'           , 'splits_predictor_scaled_historical' , ...
    'flow_predictor_type', 'scaled_historical' , ...
    'config'             , '210E' , ...
    'output_dt'          , 300 , ...
    'end_time'           , 86400 , ...
    'update_dt'          , 900 , ...
    'horizon'            , 3600 ) );

%% State estimators

fprintf('Generating report for SimulationStateEstimator ::::::::::::::\n');
SimulationStateEstimator.run_and_report_error( struct( ...
    'ppt_file'         , 'state_estimator_simulation' , ...
    'xls_file'         , 'state_estimator_simulation' , ...
    'config'           , '210E' , ...
    'output_dt'        , 300 , ...
    'end_time'         , 86400 , ...
    'update_dt'        , 900 ) );

fprintf('Generating report for LinInterpFrewayStateEstimator :::::::::\n');
LinInterpFrewayStateEstimator.run_and_report_error( struct( ...
    'ppt_file'         , 'state_estimator_lininterp' , ...
    'xls_file'         , 'state_estimator_lininterp' , ...
    'config'           , '210E' , ...
    'output_dt'        , 300 , ...
    'end_time'         , 86400 , ...
    'update_dt'        , 900 ) );

%% Prediction engine

fprintf('Generating report for Predictor sim 7200 ::::::::::::::::::::\n');
P = Predictor( struct(               ...
       'error_data_provider',  'simulation',              ...
       'model_runner',         'beats',                   ...
       'input_flow_predictor', 'simulation',              ...
       'state_estimator',      'simulation',    ...
       'configname' ,          '210E' ,                   ...
       'day' ,                 'model_day' ,              ...
       'prediction_horizon',   3600 ,                     ...
       'update_dt',            1800 ,                     ...
       'start_time',           0 ,                        ...
       'end_time',             7200  ) );
save 210E_735885_sim_7200
P.compute_prediction_error(fullfile(Folder.reports,'210E_sim_7200'))
clear P

close all
fprintf('Generating report for Predictor sim 86400 :::::::::::::::::::\n');
P = Predictor( struct(               ...
       'error_data_provider',  'simulation',              ...
       'model_runner',         'beats',                   ...
       'input_flow_predictor', 'simulation',              ...
       'state_estimator',      'simulation',    ...
       'configname' ,          '210E' ,                   ...
       'day' ,                 'model_day' ,              ...
       'prediction_horizon',   3600 ,                     ...
       'update_dt',            1800 ,                     ...
       'start_time',           0 ,                        ...
       'end_time',             86400  ) );
save 210E_735885_sim_86400
P.compute_prediction_error(fullfile(Folder.reports,'210E_sim_86400'))
clear P

close all
fprintf('Generating report for Predictor historical ::::::::::::::::::\n');
P = Predictor( struct(                                    ...
       'error_data_provider',  'pems',                    ...
       'model_runner',         'beats',                   ...
       'input_flow_predictor', 'historical',              ...
       'state_estimator',      'simulation',              ...
       'configname' ,          '210E' ,                   ...
       'day' ,                 'model_day' ,              ...
       'prediction_horizon',   3600 ,                     ...
       'update_dt',            1800 ,                     ...
       'start_time',           0 ,                        ...
       'end_time',             86400  ) );
save 210E_735885_dem_historical
P.compute_prediction_error(fullfile(Folder.reports,'210E_dem_historical'))
clear P

close all
fprintf('Generating report for Predictor scaled hist :::::::::::::::::\n');
P = Predictor( struct(                                    ...
       'error_data_provider',  'pems',                    ...
       'model_runner',         'beats',                   ...
       'input_flow_predictor', 'scaled_historical',       ...
       'state_estimator',      'simulation',              ...
       'configname' ,          '210E' ,                   ...
       'day' ,                 'model_day' ,              ...
       'prediction_horizon',   3600 ,                     ...
       'update_dt',            1800 ,                     ...
       'start_time',           0 ,                        ...
       'end_time',             86400  ) );
save 210E_735885_dem_scaled_historical
P.compute_prediction_error(fullfile(Folder.reports,'210E_dem_scaled_historical'))
clear P

close all
fprintf('Generating report for Predictor zoh :::::::::::::::::::::::::\n');
P = Predictor( struct(                                    ...
       'error_data_provider',  'pems',                    ...
       'model_runner',         'beats',                   ...
       'input_flow_predictor', 'zoh',                     ...
       'state_estimator',      'simulation',              ...
       'configname' ,          '210E' ,                   ...
       'day' ,                 'model_day' ,              ...
       'prediction_horizon',   3600 ,                     ...
       'update_dt',            1800 ,                     ...
       'start_time',           0 ,                        ...
       'end_time',             86400  ) );
save 210E_735885_dem_zoh
P.compute_prediction_error(fullfile(Folder.reports,'210E_dem_zoh'))
clear P

close all
fprintf('Generating report for Predictor lin interp ::::::::::::::::::\n');
P = Predictor( struct(               ...
       'error_data_provider',  'pems',                    ...
       'model_runner',         'beats',                   ...
       'input_flow_predictor', 'simulation',              ...
       'state_estimator',      'linear_interpolation',    ...
       'configname' ,          '210E' ,                   ...
       'day' ,                 'model_day' ,              ...
       'prediction_horizon',   3600 ,                     ...
       'update_dt',            1800 ,                     ...
       'start_time',           0 ,                        ...
       'end_time',             86400  ) );
save 210E_735885_est_lininterp
P.compute_prediction_error(fullfile(Folder.reports,'210E_est_lininterp'))
clear P

close all
fprintf('Generating report for Predictor zoh+lininter ::::::::::::::::\n');
P = Predictor( struct(                                    ...
       'error_data_provider',  'pems',                    ...
       'model_runner',         'beats',                   ...
       'input_flow_predictor', 'zoh',                     ...
       'state_estimator',      'linear_interpolation',    ...
       'configname' ,          '210E' ,                   ...
       'day' ,                 'model_day' ,              ...
       'prediction_horizon',   3600 ,                     ...
       'update_dt',            1800 ,                     ...
       'start_time',           0 ,                        ...
       'end_time',             86400  ) );
save 210E_735885
P.compute_prediction_error(fullfile(Folder.reports,'210E_735885'))
clear P

close all
fprintf('Generating report for Predictor zoh+lininter 10/20 ::::::::::\n');
P = Predictor( struct(                                    ...
       'error_data_provider',  'pems',                    ...
       'model_runner',         'beats',                   ...
       'input_flow_predictor', 'zoh',                     ...
       'state_estimator',      'linear_interpolation',    ...
       'configname' ,          '210E' ,                   ...
       'day' ,                 datenum(2014,10,20) ,      ...
       'prediction_horizon',   3600 ,                     ...
       'update_dt',            1800 ,                     ...
       'start_time',           0 ,                        ...
       'end_time',             86400  ) );
save 210E_735892
P.compute_prediction_error(fullfile(Folder.reports,'210E_735892'))
clear P